### ISSUE TITLE
Does not backup files after upgrade to 2.0

### ISSUE THREAD

**Issue by riwka** [jdaehne/BackupMODX#19]
Does not create backup files. Widget shows "Files (0 MB)."
A folder with the file named like "ziejjYvj" is created in the directory "core/components/backupmodx/backups/", but if press button "Restore a Backup", a row with files don't appear in the list.
No any error in logs. The MySQL Database backup is working.

What could be the problem?

**Comment by mcnickel** [comment]
Same behavior here. Error log:  
(ERROR @ .../core/components/backupmodx/model/backupmodx/backupmodx.class.php : 67) PHP warning: filesize(): stat failed for .../assets/backupmodx/backups/2018-12-31--154802--5ec7/2018-12-31--154802--5ec7.zip  
Zip file is not created, instead an empty folder "ziQ4IDWC".  
Database backup is ok.

Environment: 
MODX 2.6.5, PHP 7.1.5
The site is hosted at Domainfactory, where another site shows a similar error with the database backup while the file backup is fine.

**Comment by sebastian-marinescu** [comment]
I'm also unable to backup files - DB backup is fine. 

The folder is created, but no zip. 
The connector responds with this: 

```
{  
   "success":true,
   "total":1,
   "results":{  
      "filename":"2019-01-15--004324--cbaa",
      "path":"\/www\/htdocs\/somepath\/www\/assets\/backups\/2019-01-15--004324--cbaa\/",
      "files":{  
         "database":[  

         ],
         "files":{  
            "name":"2019-01-15--004324--cbaa",
            "filename":"2019-01-15--004324--cbaa.zip",
            "path":"\/www\/htdocs\/somepath\/www\/assets\/backups\/2019-01-15--004324--cbaa\/2019-01-15--004324--cbaa.zip",
            "size":0
         },
         "note":[  

         ]
      }
   }
} 
```

**Comment by jdaehne** [comment]
@riwka @mcnickel @sebastian-marinescu does it may be possible, that zip is not installed on your server, or that "zip" may need a other "alias/path" to the library? I will add some more better checking and error-handling in the next update.

**Comment by mediengaarage** [comment]
I have the same problem. Databasebackup does also not work.

`ERROR @ .../core/components/backupmodx/model/backupmodx/backupmodx.class.php : 98) PHP warning: filesize(): stat failed for .../core/components/backupmodx/backups/2019-01-15--131857--5342/2019-01-15--131857--5342.sql`

When I backup files, it create a file without ending with more than 500 MB

Provider: Domainfactory
PHP: 7.1.15
ModX: 2.7.0
Zip: enabled
Zip version: 1.13.5
Libzip version: 1.1.2

**Comment by riwka** [comment]
How to understand that need another "alias/path" to the library? Previously, archiving worked fine.

PHP: 7.1.15
ModX: 2.7.0
Zip: enabled
Zip version: 1.13.5
Libzip version: 1.1.2

**Comment by mcnickel** [comment]
I tested on various installations at different webhosters (all ModX: 2.6.5/2.7.0). I only see this error at Domainfactory and in all installations I've tested.

Either the DB backup fails (backupmodx.class.php : 67) PHP warning: filesize(): stat failed for ... .zip)
OR (never both)
the file backup fails (backupmodx/backupmodx.class.php : 98) PHP warning: filesize(): stat failed for ... .sql)

The error is always the same on a single installation, no matter if cache is cleared or login session changed. Either the db backup always fails or always the file backup. 

Weird...

**Comment by mcnickel** [comment]
At a domainfactory site I observed following behavior (SQL backup ok, file backup 0 MB):  
permissions of the backup folder are set to 750,  
the file permissions of SQL backup are set to 640,  
a file backup is created, name something like "zi3AXkFK", permissions are set to 600.  
If you download the file backup, add .zip extension and unpack it, the backup will unpack but is incomplete (zip tool also throws some related errors).  

This happens even if system settings are explicitly set to the following:  
new_file_permissions 644  
new_folder_permissions 755

**Comment by sebastian-marinescu** [comment]
I have just tested the newest [3.0.0-pl release](https://modx.com/extras/package/?id=backupmodx) from the official MODX repository and it worked in an All-Inkl shared Server environment. Both, Files and DB, got created. @riwka @mcnickel Try again - I think this issue can be closed.

**Comment by mediengaarage** [comment]
I have tested it and i get the same error as before. Files are still not backup.
The cache was cleared.

![image](https://user-images.githubusercontent.com/7986968/61623950-f4396a80-ac77-11e9-8025-f44f96c3a57a.png)

Tehere is only generated a folder in core/components/backupmodx/ but no file.

**Comment by sebastian-marinescu** [comment]
@mediengaarage But your DB now backups correctly? 
And what is the error-log saying?

**Comment by mediengaarage** [comment]
@sebastian-marinescu Yes my DB backups correctly.
I have no error-log entry.

**Comment by Jako** [comment]
That should be solved with 3.0.1. Please reopen this issue, if that's not the case.

Maybe you have to change the backupmodx.targetPath to `{core_path}backup/` or a different folder not inside of `{core_path}/components/backupmodx/`

**Comment by mediengaarage** [comment]
I still have the same problem. It is a fresh ModX installation at 1&1 IONOS.
The backup of the DB works, but not the backup of the files:
![image](https://user-images.githubusercontent.com/7986968/65782711-911ff480-e14e-11e9-9a92-f18610573211.png)

ModX: 2.7.2
PHP: 7.3.9
BackupMODX: 3.0.1
backupmodx.targetPath: {core_path}backup/

**Comment by Jako** [comment]
There is a debug mode of BackupMODX, that logs a lot in an extra backupmodx.log

**Comment by mediengaarage** [comment]
O.K. i have activate the debug mode. Here is the log-file:

[backupmodx.log](https://github.com/jdaehne/BackupMODX/files/3665386/backupmodx.log)

**Comment by Jako** [comment]
It could be caused by a timeout issue, that won't be logged at the moment. Maybe you should exclude the {base_path}/logs folder to have a smaller file backup.

**Comment by Jako** [comment]
You could also add this [patch](https://github.com/jdaehne/BackupMODX/pull/47/commits/68049bf0ab097ee063e2f30215e23ee824499621) to log the timeout (or whatever causes the shutdown)

**Comment by mediengaarage** [comment]
Great, no it works!
I will test it at the other installations where i have the same problem.
Thank you!
